# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Laboratório de Biologia do Reconhecer
name: Laboratório de Biologia do Reconhecer
description: 
  Blog de divulgação científica organizado pelo Laboratório de Biologia do Reconhecer,
  localizado na UENF em Campos dos Goytacazes/RJ
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  lbruenf

# jekyll-paginate configuration
paginate: 10

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
exclude: [vendor]
include: ["_pages"]
permalink: /posts/:title/
excerpt_separator: <!--more-->
author: LBR/UENF

host: 0.0.0.0

